import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import history from "next/router"

import { useEffect, useLayoutEffect } from "react";
import Layout from "../layout/Layout";

export default function Home() {

  useEffect(() => {
    // history.replace("/accounts")
  
   
  }, [])
  
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-center font-bold text-amber-900 text-3xl">hi</div>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  );
};
