import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import history from "next/router"

import { useEffect, useLayoutEffect } from "react";
import Layout from "../layout/Layout";
import Accounts from "../components/Dashboard/Accounts";
import Transanctions from "../components/Dashboard/Transanctions";
import Cookies from "js-cookie";

export default function Home() {

  useLayoutEffect(() => {
    let token = Cookies.get("tkn");
    if (!token) {
      
      history.replace("/auth/login")
    
    }
   
  }, [])
  
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Accounts/>
      <Transanctions/>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  );
};
